name: flexify
description: Track gym progress, visualize graphs, enjoy offline support & timers
publish_to: none
version: 1.0.75+82
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.8.3
  csv: ^6.0.0
  intl: ^0.19.0
  fl_chart: ^0.66.2
  permission_handler: ^11.3.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  dynamic_color: ^1.7.0
  sqlite3: ^2.4.0
  file_picker: ^8.0.3
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  drift_dev: ^2.15.0
  build_runner: ^2.4.8
flutter:
  uses-material-design: true
